title: Web3Privacy Now
description: Privacy advocates worldwide are coming together to discuss how to mainstream privacy within the Web3 industry. So it will become a cultural phenomenon embodying both decentralisation & anti-surveillance capitalism practices.
header:
  menu:
    - name: Home
      url: /
    - name: About
      url: /about
    - name: Research
      url: /research
    - name: Events
      url: /events
    #- name: Talks
    #  url: /talks
    #- name: Articles
    #  url: /articles
    #- name: Leaderboard
    #  url: /leaderboard
    #- name: Explorer
    #  link: explorer
    - name: News
      link: news
    - name: Docs
      link: docs
    - name: Membership
      link: membership
      url: /membership
    #- name: Manifesto
    #  url: /manifesto
  rightMenu:
    - twitter
    - mirror
    - github
    - matrix
footer:
  menu:
    - title: Docs
      ico: docs
      link: docs
    - title: "@web3privacy"
      ico: twitter
      link: twitter
    - title: Mirror
      ico: mirror
      link: mirror
    #- title: Telegram
    #  ico: telegram
    #  link: telegram
    - title: GitHub
      ico: github
      link: github
    - title: Matrix
      ico: matrix
      link: matrix
hero:
  text: |
    Privacy advocates worldwide are coming together to discuss how to mainstream privacy within the Web3 industry. So it will become a cultural phenomenon embodying both decentralisation & anti-surveillance capitalism practices.
landing:
  merch: |
    To make humans gain control over their privacy by utilizing Web3 stack. So privacy would become a cultural phenomena & active lifestyle.
  research: |
    We cultivate a culture of privacy in web3 making data free and public.  Enjoy our researches, infographics, annual reports, tools, newsletter, guidelines & more.
  mission: |
    Empower individuals to take control of their digital privacy.
    <br><br>
     We envision a world where privacy is a conscious, actively chosen lifestyle, accessible to everyone, everywhere. To turn this into reality, we need to unite our efforts and carve out a path toward a more equitable, decentralized and privacy-respecting digital space.
  event: |
    Our aim with gatherings is to build understanding and solidarity between different groups of interests, cultures, states, chains, ecosystems and backgrounds.
    <br><br>
      We aggregate web3 & non-tech people, builders, researchers, philosophers, lawyers, policymakers, hacktivists,  key players, local communities and the general public.
  topics:
    - Identity
    - Private Messaging
    - Regulation vs. Privacy
    - On-chain Privacy
    - Privacy wars
    - Privacy activism
    - Network states
    - "R&D: ZK, MPC, THE"
    - Fullstack Privacy
    - Lunarpunk vs. Solarpunk
    - Human rights DAO
  follow:
    - name: "@web3privacy"
      link: twitter
      text: 800+ followers
      ico: twitter
    #- name: "@web3privacy.info"
    #  link: bluesky
    #  text: Bluesky
    #  ico: bluesky
    - name: Telegram
      link: telegram
      text: Telegram group
      ico: telegram
    - name: Mirror
      link: mirror
      text: Articles, reports, etc.
      ico: mirror
    - name: YouTube
      link: youtube
      text: Videos
      ico: youtube
  coord:
    - name: Documentation
      link: docs
      text: About our initiative
      ico: docs
    - name: GitHub
      link: github
      text: Source-code repositories
      ico: github
    - name: Matrix
      link: matrix
      text: Real-time communication
      ico: matrix
    - name: Forum
      link: forum
      text: Community discussion
      ico: forum
  community: |
    Our aim with gatherings is to bring together key players, different perspectives, skills and visions. We aggregate tech and non tech people, key players and contributors, builders, researchers, philosophers, lawyers, policymakers, activists, local communities and general public.
organisation:
  table:
    events:
      - objective: 6+ Events in different countires
        details: |
          1 Summit + 1 Hackathon + 3 Meetups [target outreach: 1000 people IRL]

        height: 50

    research:
      - objective: Privacy in Ethereum
        details: |
          The most comprehensive report of privacy
        url: /research/ethereum
        height: 50
      - objective: Use cases DB update & improve (500 → 700 privacy projects
        details: |
          Most extensive web3 db of privacy-enhancing solutions
        url: /research/ethereum
        height: 80
      - objective: Privacy Annual Report (150+ pages)
        details: |
          Showcase all happenings and achievements of the year (3rd Edition)
        url: /research/ethereum
        height: 60
      - objective: Privacy Awards
        details: |
          Annual vote of most popular and interesting privacy projects
        url: /research/ethereum
        height: 60
      - objective: Week in Privacy
        details: |
          Newsletter with round-up of the most important privacy news
        url: /research/ethereum
        height: 60
      - objective: Monthly Infographics & Articles
        details: |
          Release of useful material for tech & general public
        url: /research/ethereum
        height: 30
    tools:
      - objective: Privacy Explorer V.2
        details: |
          300 services, 5 new categories, improve scoring model
        url: /research/ethereum
        height: 50
      - objective: Privacy Routing tool (V0.1 release)
        details: |
          Help users to choose the right service for their transactions
        url: /research/ethereum
        height: 50
    education:
      - objective: Academy
        details: |
          101 privacy educational track with our partners

        height: 50
      - objective: Hackathon Curation Pack
        details: |
          Guidelines to help the builders uderstand actual issues
        url: /research/ethereum
        height: 60
      - objective: Privacy Guidelines for the public
        details: |

        url: /research/ethereum
        height: 50
