title: Web3Privacy Now
description: Privacy advocates worldwide are coming together to discuss how to mainstream privacy within the Web3 industry. So it will become a cultural phenomenon embodying both decentralisation & anti-surveillance capitalism practices.
header:
  menu:
    - name: Home
      url: /
    - name: About
      url: /about
    - name: Research
      url: /research
    - name: Events
      url: /events
    #- name: Talks
    #  url: /talks
    #- name: Articles
    #  url: /articles
    #- name: Leaderboard
    #  url: /leaderboard
    - name: Explorer
      link: explorer
    - name: News
      link: news
    - name: Docs
      link: docs
    #- name: Manifesto
    #  url: /manifesto
  rightMenu:
    - twitter
    - mirror
    - github
    - matrix
footer:
  menu:
    - title: Docs
      ico: docs
      link: docs
    - title: "@web3privacy"
      ico: twitter
      link: twitter
    - title: Mirror
      ico: mirror
      link: mirror
    #- title: Telegram
    #  ico: telegram
    #  link: telegram
    - title: GitHub
      ico: github
      link: github
    - title: Matrix
      ico: matrix
      link: matrix
hero:
  text: |
    Privacy advocates worldwide are coming together to discuss how to mainstream privacy within the Web3 industry. So it will become a cultural phenomenon embodying both decentralisation & anti-surveillance capitalism practices.
landing:
  mission: |
    To make humans gain control over their privacy by utilizing Web3 stack. So privacy would become a conscious choice (active lifestyle) & be accessible to everyone worldwide.
    <br><br>
    Privacy advocates worldwide are coming together to discuss how to mainstream privacy within the Web3 industry. So it will become a cultural phenomenon embodying both decentralisation.
  topics:
    - Identity
    - Private Messaging
    - Regulation vs. Privacy
    - On-chain Privacy
    - Privacy wars
    - Privacy activism
    - Network states
    - "R&D: ZK, MPC, THE"
    - Fullstack Privacy
    - Lunarpunk vs. Solarpunk
    - Human rights DAO
  follow:
    - name: "@web3privacy"
      link: twitter
      text: 800+ followers
      ico: twitter
    #- name: "@web3privacy.info"
    #  link: bluesky
    #  text: Bluesky
    #  ico: bluesky
    - name: Telegram
      link: telegram
      text: Telegram group
      ico: telegram
    - name: Mirror
      link: mirror
      text: Articles, reports, etc.
      ico: mirror
    - name: YouTube
      link: youtube
      text: Videos
      ico: youtube
  coord:
    - name: Documentation
      link: docs
      text: About our initiative
      ico: docs
    - name: GitHub
      link: github
      text: Source-code repositories
      ico: github
    - name: Matrix
      link: matrix
      text: Real-time communication
      ico: matrix
    - name: Forum
      link: forum
      text: Community discussion
      ico: forum
  community: |
    Our aim with gatherings is to bring together key players, different perspectives, skills and visions. We aggregate tech and non tech people, key players and contributors, builders, researchers, philosophers, lawyers, policymakers, activists, local communities and general public.
